---
- name: Import Icinga GPG key
  ansible.builtin.rpm_key:
    key: https://packages.icinga.com/icinga.key
    state: present

- name: Install Icinga2 RPM release
  ansible.builtin.dnf:
    name: https://packages.icinga.com/epel/icinga-rpm-release-8-latest.noarch.rpm
    state: present

- name: Install icinga2 and compat-openssl10
  ansible.builtin.dnf:
    name:
      - icinga2
      - compat-openssl10
    state: present
