---
- name: Set plugin path for Debian/Ubuntu
  ansible.builtin.set_fact:
    _icinga2_plugin_path: "{{ icinga2_plugin_path_debian }}"
  when: ansible_os_family == "Debian"

- name: Set plugin path for RedHat
  ansible.builtin.set_fact:
    _icinga2_plugin_path: "{{ icinga2_plugin_path_redhat }}"
  when: ansible_os_family == "RedHat"

- name: Set plugin path for SLES
  ansible.builtin.set_fact:
    _icinga2_plugin_path: "{{ icinga2_plugin_path_sles }}"
  when: ansible_os_family == "Suse"

- name: Copy check_mem.pl
  ansible.builtin.copy:
    src: check_mem.pl
    dest: "{{ _icinga2_plugin_path }}/check_mem.pl"
    owner: root
    group: root
    mode: "0755"
