---
- name: Install EPEL
  ansible.builtin.yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Enable subscription-manager optional repos
  ansible.builtin.shell: |
    set -o pipefail
    subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-server-optional-rpms
    subscription-manager repos --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false

- name: Import Icinga GPG key
  ansible.builtin.rpm_key:
    key: https://packages.icinga.com/icinga.key
    state: present

- name: Install Icinga2 RPM release
  ansible.builtin.yum:
    name: "https://packages.icinga.com/epel/icinga-rpm-release-{{ ansible_distribution_major_version }}-latest.noarch.rpm"
    state: present

- name: Install icinga2 and nagios-plugins
  ansible.builtin.yum:
    name:
      - icinga2
      - nagios-plugins-all
    state: present
  failed_when: false
