---
- name: Restart icinga2
  ansible.builtin.service:
    name: icinga2
    state: restarted

- name: Enable icinga2
  ansible.builtin.service:
    name: icinga2
    enabled: true
    state: "{{ icinga2_service_state }}"
